### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by jackcarlisle** [reviewedocode/reviewedo#3]
# Task list 

- [ ] hook up search with a form
- [ ] design the search results page
- [ ] fix the landing page
- [ ] add search bar to homepage
- [ ] add search bar to search results page
- [ ] add pagination for search results
- [ ] add linked in log in
- [ ] create company page
- [ ] add review functionality for logged in users
